[package]
name = "nesium-flutter"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "nesium_flutter"
crate-type = ["staticlib", "cdylib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[dependencies]
nesium-core.path = "../nesium-core"
flutter_rust_bridge = "=2.11.1"
anyhow.workspace = true
nesium-runtime.path = "../nesium-runtime"
