[package]
name = "nesium-flutter"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "nesium_flutter"
crate-type = ["staticlib", "cdylib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[dependencies]
nesium-core.workspace = true
flutter_rust_bridge.workspace = true
anyhow.workspace = true
nesium-runtime.workspace = true
nesium-support.workspace = true

[target.'cfg(any(target_os = "android", target_os = "windows", target_os = "linux"))'.dependencies]
mimalloc = { workspace = true, optional = true }

[features]
default = ["mimalloc"]
mimalloc = ["dep:mimalloc"]

[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
ndk-context.workspace = true
libc.workspace = true
