[package]
name = "nesium-esp32"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
nesium-core.workspace = true
anyhow.workspace = true
esp-idf-sys = { workspace = true, features = ["binstart"] }
