[workspace]
resolver = "3"
members = [
    "crates/nesium-egui",
    "crates/nesium-core",
    "crates/nesium-esp32",
    "crates/libretro-bridge",
    "crates/nesium-libretro",
    "crates/nesium-flutter",
    "crates/nesium-blip",
    "crates/nesium-audio",
]
default-members = [
    "crates/nesium-egui",
    "crates/nesium-core",
    "crates/libretro-bridge",
    "crates/nesium-libretro",
    "crates/nesium-flutter",
    "crates/nesium-blip",
    "crates/nesium-audio",
]

[profile.test]
opt-level = 2
debug = true

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
debug = false

[workspace.package]
license = "GPL-3.0-or-later"

[workspace.dependencies]
bitflags = "2.10.0"
esp-idf-sys = "0.36"
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
ctor = "0.6.2"
dyn-clone = "1.0.20"
eframe = "0.33.2"
gilrs = "0.11"
once_cell = "1.19"
bindgen = "0.72"
ureq = "2.9"
bincode = "2.0.1"
anyhow = "1.0"
sdl2 = "0.35"
egui_glow = "0.33.2"
glow = "0.13"
rfd = "0.14"
fontdb = "0.23"
ttf-parser = "0.25"
cpal = "0.16.0"
ringbuf = "0.4.8"
