[workspace]
resolver = "3"
members = [
    "crates/nesium",
    "crates/nesium-core",
    "crates/libretro-bridge",
    "crates/nesium-libretro",
]

[workspace.package]
license = "MIT"

[workspace.dependencies]
bitflags = "2.10.0"
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
ctor = "0.6.1"
dyn-clone = "1.0.20"
egui = "0.33.2"
once_cell = "1.19"
bindgen = "0.72"
ureq = "2.9"
