[workspace]
resolver = "3"
members = ["crates/nesium-core"]

[workspace.package]
license = "MIT"

[workspace.dependencies]
bitflags = "2.10.0"
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
ctor = "0.6.1"
dyn-clone = "1.0.20"
