[package]
name = "nesium-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
boxed-ram = []

[dependencies]
bitflags.workspace = true
dyn-clone.workspace = true
bincode.workspace = true
once_cell.workspace = true

[dev-dependencies]
rand.workspace = true
ctor.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
