[package]
name = "nesium-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
ctor = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
