[package]
name = "nesium-core"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[features]
default = []
boxed-ram = []

[profile.test]
opt-level = 2
debug = true

[dependencies]
bitflags.workspace = true
dyn-clone.workspace = true
bincode.workspace = true
tracing.workspace = true
nesium-blip = { path = "../nesium-blip" }

[dev-dependencies]
rand.workspace = true
ctor.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
once_cell.workspace = true
