[package]
name = "nesium-libretro"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lints]
workspace = true

[lib]
name = "nesium_libretro"
crate-type = ["cdylib"]

[dependencies]
libretro-bridge.workspace = true
nesium-core.workspace = true
once_cell.workspace = true
