[package]
name = "nesium-icon"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
skia-safe = { workspace = true, features = ["gl", "svg"] }
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
