[package]
name = "nesium-support"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
nesium-core = { workspace = true, features = ["savestate-postcard"] }
lz4_flex.workspace = true
bitflags.workspace = true
thiserror.workspace = true
hex = "0.4.3"
